### ISSUE TITLE
Where is the code of diffusion model and how can I get the dataset of DrugOOD and GOOD you have preprocessed?

### ISSUE THREAD

**Issue by fanxiaoyu0** [se7esx/GRMOOD#1]

**Comment by se7esx** [comment]
Sorry for not replying to you in time since I am on academic leave in the past weeks. About diffusion model code, you can be found in utils and utils/model, the details you can be found at https://github.com/harryjo97/GDSS. About the GOOD and DrugOOD, please refer to https://github.com/divelab/GOOD/?tab=readme-ov-file and https://github.com/tencent-ailab/DrugOOD for installation
