### ISSUE TITLE
What will happen if you don't generate prototypical graph and just use the molecule in ID dataset as the prototypical graph and use FGW do the same thing to detect OOD data? Is generating prototypical graph really necessary?

### ISSUE THREAD

**Issue by fanxiaoyu0** [se7esx/GRMOOD#2]

**Comment by se7esx** [comment]
Thank you for your valuable question. When our paper was under peer review, the reviewers asked the same question, for which we conducted experimental verification

| Method| Metric| DrugOOD-IC50-Scaffold | DrugOOD-IC50-Size
|   :----:|   :----: |    :---: |     :---: |  
|| AUROC  | **91.57±1.32** | **93.84±1.53** |
|Prototypical graphs| AURP | **90.12±0.71**   | **94.85±2.03** |
|| FPR95 | **19.42±0.22**  | **15.57±1.03** |
|| AUROC| 42.85±5.4  | 41.14±4.8 |
|Random training samples| AURP| 47.85±3.7   | 48.66±5.6 |
|| FPR95 | 92.67±1.2   | 90.15±2.2 |

Since the purpose of proposing the prototype graph is to ensure that it has the maximum similarity of and ID and the minimum similarity of OOD, the strategy of randomly selecting training samples cannot guarantee this
